on: 
  workflow_dispatch:
  
# env:
#   KUBCONFIG: ${{ secrets.KUBE_CONFIG }}

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: kubectl
        run: |
          az aks get-credentials --resource-group Go1PercentPlatform --name go1percent-aks-dev
          kubectl get po
