on: 
  workflow_dispatch:
  
env:
  KUBECONFIG: ${{ secrets.KUBE_CONFIG }}

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
   
    - run: |
        kubectl get po -A
